project:
  type: website

website:
  favicon: "icons/asset 6.png"
  site-url: 'https://cosmic-charade.netlify.app'
  title: "Cosmic Charadeü™êüå†"
  open-graph:
    image: "logo-with-bg-2.jpg"
  navbar:
    left:
       - text: Home
         file: index.qmd
       - href: about.qmd
       # - text: Submit Your Blog
       #   file: guidelines.qmd
       - href: posts.qmd
       - href: liter.qmd
       - text: Cosmic Courses
         menu:
          # - text: R for Everyone
          #   href: r4e.pdf
          - text: Computational Thinking with R + Python 
            href: actrp.pdf
       - href: mag.qmd
       - text: Cosmic Squad
         href: squad_new3.qmd
       - text: Donation Box
         href: donate.qmd
    right:
      # - href: bb.qmd
      - icon: envelope
        href: mailto:cosmiccharade0@gmail.com
      - icon: instagram
        href: https://www.instagram.com/bismoykar_bramhanda/
      - icon: linkedin
        href: https://linkedin.com/company/bismoykar-bramhanda
      - icon: whatsapp
        href: https://chat.whatsapp.com/BwGDsLPHX6i1ID4711I2DQ
      - icon: telegram
        href: https://t.me/bismoykar_bramhanda_cc
      - icon: youtube
        href: https://youtube.com/@cosmiccharade33?si=m3B9lqSqcioNJVtb
  page-footer: 
    left: Proudly made with Quarto üíô <br> Copyright ¬© 2024 | Contact us <br> [Privacy Policy](privacy_policy.qmd)
    right: "Registered under Govt. of India <br> UDYAM-WB-08-0072647"
  margin-footer: subscribe.html
  # margin-header: guidelines.qmd
  reader-mode: true
  # page-footer: href: date_time.qmd
      #   href: https://github.com/
      # - icon: twitter
      #   href: https://twitter.com
  cookie-consent: 
    type: express
    style: interstitial
  google-analytics:
    tracking-id: "G-JGPEZ5562L"
    anonymize-ip: true

# filters:
#   - snow

format:
  html:
    backgroundcolor: "#FFFEF4"
    theme:
      light: flatly
      # dark: solar
    css: styles.css

editor: visual

execute:
  freeze: auto
